#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# deploy_admin_ui.sh — Build and deploy the OTA admin web interface to S3
#
# Can be run standalone or called by deploy.sh.
# Reads the same deploy.config as deploy.sh.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
export AWS_PAGER="" PAGER=cat

DIR="$(cd "$(dirname "$0")" && pwd)"

# Load config if not already loaded (allow deploy.sh to pre-source it)
if [[ -z "${PREFIX:-}" ]]; then
  CONFIG_FILE="${DEPLOY_CONFIG:-${DIR}/deploy.config}"
  if [[ -f "$CONFIG_FILE" ]]; then
    set -a; source "$CONFIG_FILE"; set +a
  else
    echo "ERROR: deploy.config not found. See deploy.config.template."
    exit 1
  fi
fi

REGION="${REGION:-ap-south-1}"
PREFIX="${PREFIX:-digilux}"
ADMIN_UI_BUCKET="${ADMIN_UI_BUCKET:-}"
BRAND_NAME="${BRAND_NAME:-OTA Admin}"
LOGO_FILE="${LOGO_FILE:-}"

if [[ -z "$ADMIN_UI_BUCKET" ]]; then
  echo "ADMIN_UI_BUCKET not set — skipping admin UI deployment."
  exit 0
fi

# ── Find the admin UI repo ────────────────────────────────────────────────────
# Try: explicit path → sibling directory → common names
find_ui_repo() {
  if [[ -n "${ADMIN_UI_REPO_PATH:-}" && -d "$ADMIN_UI_REPO_PATH" ]]; then
    echo "$ADMIN_UI_REPO_PATH"; return
  fi
  # Search relative to the ota/infrastructure directory
  local CANDIDATES=(
    "${DIR}/../../admin-web-interface"
    "${DIR}/../../../admin-web-interface"
    "${DIR}/../../digilux-ota-admin-ui"
    "${HOME}/maney/digilux/aws-cloud/admin-web-interface"
  )
  for C in "${CANDIDATES[@]}"; do
    if [[ -f "${C}/package.json" ]]; then
      echo "$(cd "$C" && pwd)"; return
    fi
  done
  echo ""
}

UI_REPO=$(find_ui_repo)
if [[ -z "$UI_REPO" ]]; then
  echo "ERROR: Could not find admin UI repository."
  echo "       Set ADMIN_UI_REPO_PATH in deploy.config to the full path."
  exit 1
fi
echo "==> Admin UI repo: $UI_REPO"

# ── Copy logo file ────────────────────────────────────────────────────────────
if [[ -n "$LOGO_FILE" && -f "$LOGO_FILE" ]]; then
  EXT="${LOGO_FILE##*.}"
  DEST_LOGO="brand-logo.${EXT}"
  cp "$LOGO_FILE" "${UI_REPO}/public/${DEST_LOGO}"
  echo "==> Logo: $LOGO_FILE → public/${DEST_LOGO}"
  VITE_LOGO_FILENAME="$DEST_LOGO"
else
  echo "==> Logo: using default placeholder (brand-logo.png)"
  VITE_LOGO_FILENAME="brand-logo.png"
fi

# ── Generate .env.production ──────────────────────────────────────────────────
API_BASE="${ADMIN_UI_API_BASE:-https://${API_GATEWAY_ID}.execute-api.${REGION}.amazonaws.com/${API_GATEWAY_STAGE}/api/v1}"
COGNITO_URL="${ADMIN_UI_COGNITO_URL:-https://cognito-idp.${REGION}.amazonaws.com/}"
COGNITO_CLIENT="${ADMIN_UI_COGNITO_CLIENT:-}"

cat > "${UI_REPO}/.env.production" << ENV
# Auto-generated by deploy_admin_ui.sh — do not edit by hand
VITE_API_BASE=${API_BASE}
VITE_COGNITO_URL=${COGNITO_URL}
VITE_COGNITO_CLIENT=${COGNITO_CLIENT}
VITE_BRAND_NAME=${BRAND_NAME}
VITE_APP_SUBTITLE=OTA Admin
VITE_LOGO_FILENAME=${VITE_LOGO_FILENAME}
ENV

echo "==> .env.production written"
cat "${UI_REPO}/.env.production"

# ── Build ─────────────────────────────────────────────────────────────────────
echo ""
echo "==> npm install"
cd "$UI_REPO"
npm install --silent

echo "==> npm run build"
npm run build

# ── Deploy to S3 ─────────────────────────────────────────────────────────────
echo ""
echo "==> Syncing to s3://${ADMIN_UI_BUCKET}/"
aws s3 sync dist/ "s3://${ADMIN_UI_BUCKET}/" \
  --delete \
  --region "$REGION" \
  --cache-control "public,max-age=31536000,immutable" \
  --exclude "index.html"

# index.html must NOT be cached — always serve the latest shell
aws s3 cp dist/index.html "s3://${ADMIN_UI_BUCKET}/index.html" \
  --region "$REGION" \
  --cache-control "no-cache,no-store,must-revalidate" \
  --content-type "text/html"

echo "    Synced."

# Optional: invalidate CloudFront if distribution ID is known
if [[ -n "${ADMIN_UI_CLOUDFRONT_DIST_ID:-}" ]]; then
  echo "==> Invalidating CloudFront distribution: $ADMIN_UI_CLOUDFRONT_DIST_ID"
  aws cloudfront create-invalidation \
    --distribution-id "$ADMIN_UI_CLOUDFRONT_DIST_ID" \
    --paths "/*" > /dev/null
  echo "    Invalidation submitted."
fi

echo ""
echo "Admin UI deployed to s3://${ADMIN_UI_BUCKET}/"
